# Site settings
title: Zero2Flag
description: Projeto Zero2Flag 
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "/zero2flag/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://raphabarreto.com.br" # the base hostname & protocol for your site

pagination:

  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  per_page: 5

# Social
facebook: facebook
twitter: twitter
github:  github

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate-v2


# Settings for rake task
safe: False
lsi: False
username: raphabarreto #github username
repo: zero2flag #github repository
branch: master #branch
relative_source: ../zero2flag/ #source directory
destination: ../zero2flag-pages/ #destination directory
production_url:  https://raphabarreto.com/
source_url:  https://github.com/raphabarreto/zero2flag #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml